providers = ["...", "python"]

[phases.install]
aptPkgs = ["...", "python3-pip"]

# Install uv and sync dependencies
cmds = [
  "curl -LsSf https://astral.sh/uv/install.sh | sh",
  "uv sync --frozen --no-dev"
]

# Cache uv directories for faster rebuilds
cacheDirectories = ["~/.cache/uv", ".venv"]

[start]
cmd = "uv run uvicorn nixpack_template.server:app --host 0.0.0.0 --port 3000 --workers 4"

# nixpacks build . -t my-app
# sudo docker run -p 3000:3000 my-app
