name: Test Nixpacks Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-nixpack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run tests
        run: |
          uv sync --all-groups
          mkdir -p htmldoc/nixpack_template
          uv run pytest
          uv run pdoc --html --force --config latex_math=True -o htmldoc nixpack_template
          uv run coverage html -d htmldoc/coverage --rcfile tests/coverage.conf
          uv run coverage xml -o htmldoc/coverage/coverage.xml --rcfile tests/coverage.conf
          uv run docstr-coverage src/nixpack_template -miP -sp -is -idel --skip-file-doc --badge=htmldoc/nixpack_template/doc_badge.svg
          uv run genbadge coverage -l -i htmldoc/coverage/coverage.xml -o htmldoc/nixpack_template/cov_badge.svg

      # Install nixpacks (via cargo)
      - name: Install Nixpacks
        run: |
          curl -fsSL https://nixpacks.com/install.sh | bash
          nixpacks --version

      # Build Docker image with Nixpacks
      - name: Build image
        run: |
          nixpacks build . -t myapp:latest

      # Run tests inside the container
      - name: Run tests
        run: |
          docker run --rm  myapp sh -c "curl localhost:3000"
